apiVersion: v1
name: imagepullsecrets
description: Dynamically manage pull secrets for images
home: https://banzaicloud.com

maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
sources:
- https://github.com/banzaicloud/backyards

version: 0.2.7
appVersion: 0.2.7
